---
- name: Configurer les serveurs web (nginx + page HTML)
  hosts: web
  become: true
  roles:
    - hardening
    - webserver
    - node_exporter

- name: Configurer le serveur FTP (vsftpd)
  hosts: ftp
  become: true
  roles:
    - hardening
    - ftpserver
    - node_exporter

- name: Déployer la supervision (Prometheus + Grafana)
  hosts: monitoring
  become: true
  roles:
    - hardening
    - monitoring
